# Sesi 9

In [1]:
!pip install scipy

The system cannot find the path specified.
You should consider upgrading via the 'c:\users\rakay\appdata\local\programs\python\python38\python.exe -m pip install --upgrade pip' command.


In [2]:
import math
import statistics
import numpy as np
import scipy.stats
import pandas as pd

In [3]:
x = [8.0, 1, 2.5, 4, 28.0]
x_with_nan = [8.0, 1, 2.5, math.nan, 4, 28.0]

print(x)
print(x_with_nan)

[8.0, 1, 2.5, 4, 28.0]
[8.0, 1, 2.5, nan, 4, 28.0]


In [4]:
y, y_with_nan = np.array(x), np.array(x_with_nan)

print(y)
print(y_with_nan)

[ 8.   1.   2.5  4.  28. ]
[ 8.   1.   2.5  nan  4.  28. ]


In [5]:
z, z_with_nan = pd.Series(x), pd.Series(x_with_nan)

print(z)
print(z_with_nan)

0     8.0
1     1.0
2     2.5
3     4.0
4    28.0
dtype: float64
0     8.0
1     1.0
2     2.5
3     NaN
4     4.0
5    28.0
dtype: float64


## Measure of Central Tendency

In [6]:
# Mean

In [7]:
# Pure Python
mean_ = sum(x) / len(x)
mean_

8.7

In [8]:
# Python Stats
mean_ = statistics.mean(x)
mean_

8.7

In [9]:
mean_ = statistics.mean(x_with_nan)
mean_

nan

In [10]:
# Numpy
mean_ = np.mean(y)
mean_

8.7

In [11]:
y.mean()

8.7

In [13]:
print(y_with_nan.mean())
print(np.mean(y_with_nan))

nan
nan


In [14]:
np.nanmean(y_with_nan)

8.7

In [15]:
# Pandas
z.mean()

8.7

In [16]:
z_with_nan.mean()

8.7

In [17]:
# Weighted Mean

In [18]:
x

[8.0, 1, 2.5, 4, 28.0]

In [19]:
w = [0.1, 0.2, 0.3, 0.25, 0.15]

In [20]:
w = np.array(w)

In [21]:
np.average(y, weights=w)

6.95

In [22]:
np.average(z, weights=w)

6.95

In [23]:
# Harmonic Mean

In [24]:
statistics.harmonic_mean(x)

2.7613412228796843

In [25]:
scipy.stats.hmean(y)

2.7613412228796843

In [26]:
# Geometric Mean

In [27]:
scipy.stats.gmean(y)

4.67788567485604

In [28]:
scipy.stats.gmean(z)

4.67788567485604

In [30]:
# Median

In [31]:
x

[8.0, 1, 2.5, 4, 28.0]

In [32]:
x[:-1]

[8.0, 1, 2.5, 4]

In [33]:
statistics.median_low(x[:-1])

2.5

In [34]:
statistics.median_high(x[:-1])

4

In [35]:
statistics.median(x[:-1])

3.25

In [38]:
x_with_nan

[8.0, 1, 2.5, nan, 4, 28.0]

In [36]:
statistics.median(x_with_nan)

6.0

In [39]:
statistics.median(x)

4

In [41]:
# Numpy
np.median(y)

4.0

In [42]:
np.median(x[:-1])

3.25

In [43]:
# Modus

In [44]:
u = [2, 3, 2, 8, 12]
v = [12, 15, 12, 15, 21, 15, 12]

In [45]:
statistics.mode(u)

2

In [46]:
u, v = np.array(u), np.array(v)

In [47]:
scipy.stats.mode(u)

ModeResult(mode=array([2]), count=array([2]))

In [48]:
scipy.stats.mode(v)

ModeResult(mode=array([12]), count=array([3]))

## Measure of Variability

In [49]:
# Variance

In [51]:
# Stats
statistics.variance(x)

123.2

In [52]:
# Numpy
np.var(y, ddof=1)

123.19999999999999

In [53]:
# Pandas
z.var(ddof=1)

123.19999999999999

In [54]:
## Std Deviation

In [55]:
statistics.stdev(x)

11.099549540409287

In [56]:
np.std(y, ddof=1)

11.099549540409285

In [57]:
z.std(ddof=1)

11.099549540409285

In [58]:
## Skewness

In [59]:
x

[8.0, 1, 2.5, 4, 28.0]

In [60]:
y

array([ 8. ,  1. ,  2.5,  4. , 28. ])

In [61]:
scipy.stats.skew(y, bias=False)

1.9470432273905927

In [62]:
scipy.stats.skew(y_with_nan, bias=False)

nan

In [63]:
z.skew()

1.9470432273905924

In [64]:
z_with_nan.skew()

1.9470432273905924

In [65]:
# Percentiles

In [66]:
x = [-5.0, -1.1, 0.1, 2.0, 8.0, 12.8, 21.0, 25.8, 41.0]

In [67]:
statistics.quantiles(x, n=2)

[8.0]

In [68]:
y = np.array(x)

In [69]:
np.percentile(y, 5)

-3.44

In [70]:
np.percentile(y, 95)

34.919999999999995

In [71]:
np.percentile(y, [25, 50, 75])

array([ 0.1,  8. , 21. ])

In [72]:
z = pd.Series(y)

In [73]:
z.quantile(0.05)

-3.44

In [74]:
z.quantile(0.95)

34.919999999999995

In [75]:
z.quantile([0.25, 0.5, 0.75])

0.25     0.1
0.50     8.0
0.75    21.0
dtype: float64

In [76]:
# Range

In [77]:
np.ptp(y)

46.0

In [78]:
np.ptp(z)

46.0

In [79]:
# Summary of Desc Stats

In [80]:
result = scipy.stats.describe(y, ddof=1, bias=False)

In [81]:
result

DescribeResult(nobs=9, minmax=(-5.0, 41.0), mean=11.622222222222222, variance=228.75194444444446, skewness=0.9249043136685094, kurtosis=0.14770623629658886)

In [82]:
result.mean

11.622222222222222

In [83]:
result.variance

228.75194444444446

In [84]:
result = z.describe()

In [85]:
result

count     9.000000
mean     11.622222
std      15.124548
min      -5.000000
25%       0.100000
50%       8.000000
75%      21.000000
max      41.000000
dtype: float64

In [86]:
result['mean']

11.622222222222222

In [87]:
result['max']

41.0

In [88]:
# Covariance

In [89]:
x = list(range(-10, 11))

In [90]:
x

[-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [91]:
y = [0, 2, 2, 2, 2, 3, 3, 6, 7, 4, 7, 6, 6, 9, 4, 5, 5, 10, 11, 12, 14]

In [92]:
x_, y_ = np.array(x), np.array(y)
x__, y__ = pd.Series(x), pd.Series(y)

In [93]:
np.cov(x_, y_)

array([[38.5       , 19.95      ],
       [19.95      , 13.91428571]])

In [94]:
x__.cov(y__)

19.95

In [95]:
# Correlation Coefficient

In [96]:
# Numpy
np.corrcoef(x_, y_)

array([[1.        , 0.86195001],
       [0.86195001, 1.        ]])

In [97]:
# Scipy
scipy.stats.pearsonr(x_, y_)

(0.8619500056316061, 5.122760847201135e-07)

In [98]:
# Pandas
x__.corr(y__)

0.8619500056316061