# Sesi 4

Numpy

In [1]:
import numpy as np

## Making an Array

In [3]:
firstArray = np.array([1, 2, 3, 4])

In [4]:
firstArray

array([1, 2, 3, 4])

In [13]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [44]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [14]:
np.empty(6)

array([0., 0., 0., 0., 0., 0.])

In [16]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
np.arange(2, 10, 4)

array([2, 6])

## Add, Remove, Sort

In [25]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [26]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [29]:
arr = np.append(arr, [1, 2])

In [30]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [31]:
np.append([11, 12], arr)

array([11, 12,  1,  2,  3,  4,  5,  6,  7,  8,  1,  2])

In [32]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [33]:
np.delete(arr, 1)

array([1, 3, 4, 5, 6, 7, 8, 1, 2])

In [34]:
np.sort(arr)

array([1, 1, 2, 2, 3, 4, 5, 6, 7, 8])

In [35]:
array_example = np.array([[[0, 1, 2, 3],
                          [0, 1, 2, 3]],
                          
                          [[0, 1, 2, 3],
                          [0, 1, 2, 3]],
                         
                          [[0, 1, 2, 3],
                          [0, 1, 2, 3]]])

## Shape and Size

In [36]:
array_example

array([[[0, 1, 2, 3],
        [0, 1, 2, 3]],

       [[0, 1, 2, 3],
        [0, 1, 2, 3]],

       [[0, 1, 2, 3],
        [0, 1, 2, 3]]])

In [37]:
array_example.ndim

3

In [38]:
array_example.size

24

In [39]:
array_example.shape

(3, 2, 4)

## Reshape

In [46]:
a = np.arange(6)

In [47]:
a

array([0, 1, 2, 3, 4, 5])

In [49]:
a.reshape(3, 2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [50]:
a.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [51]:
a.reshape(6, 1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [52]:
a.reshape(1, 6)

array([[0, 1, 2, 3, 4, 5]])

## Convert 1D to 2D

In [54]:
a

array([0, 1, 2, 3, 4, 5])

In [55]:
a.shape

(6,)

In [62]:
a2 = a[np.newaxis, :]

In [63]:
a2

array([[0, 1, 2, 3, 4, 5]])

In [64]:
a2.shape

(1, 6)

In [66]:
a3 = a[:, np.newaxis]

In [67]:
a3.shape

(6, 1)

In [68]:
a

array([0, 1, 2, 3, 4, 5])

In [71]:
b2 = np.expand_dims(a, axis=1)

In [74]:
b2.shape

(6, 1)

In [72]:
b3 = np.expand_dims(a, axis=0)

In [75]:
b3.shape

(1, 6)

## Indexing and Slicing

In [76]:
a

array([0, 1, 2, 3, 4, 5])

In [79]:
print(a)
print(a[0])
print(a[2])

[0 1 2 3 4 5]
0
2


In [81]:
a[0:4]

array([0, 1, 2, 3])

In [82]:
a[2:]

array([2, 3, 4, 5])

In [83]:
a[:4]

array([0, 1, 2, 3])

In [84]:
a[-1]

5

In [85]:
newArray = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])

In [86]:
newArray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [87]:
newArray[newArray>5]

array([ 6,  7,  8,  9, 10, 11, 12])

In [90]:
newArray[newArray<5]

array([1, 2, 3, 4])

In [91]:
newArray[(newArray>2) & (newArray< 11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

## Create Array from Existing Data

In [93]:
arr = np.arange(1, 11)

In [94]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [96]:
arr1 = arr[3:8]

In [97]:
arr1

array([4, 5, 6, 7, 8])

In [98]:
a_1 = np.array([[1, 1],
               [2, 2]])

In [99]:
a_2 = np.array([[3, 3],
               [4, 4]])

In [103]:
print(a_1)
print(a_2)

[[1 1]
 [2 2]]
[[3 3]
 [4 4]]


In [106]:
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [107]:
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

## Array Operations

In [108]:
data = np.array([1, 2])

In [109]:
ones = np.ones(2)

In [110]:
data + ones

array([2., 3.])

In [111]:
data.sum()

3

In [112]:
a

array([0, 1, 2, 3, 4, 5])

In [113]:
a.sum()

15

In [121]:
b = np.array([[1, 2], [1, 2]])

In [122]:
b

array([[1, 2],
       [1, 2]])

In [123]:
b.sum()

6

In [124]:
b.sum(axis=0)

array([2, 4])

In [125]:
b.sum(axis=1)

array([3, 3])

In [127]:
data * 2

array([2, 4])

In [128]:
data

array([1, 2])

In [129]:
data = np.array([[1, 2, 3, 4, 5, 6],
                [7, 8, 9, 10, 11, 12],
                [13, 14, 15, 16, 17, 18]])

In [130]:
data

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [131]:
data.sum()

171

In [132]:
data.sum(axis=0)

array([21, 24, 27, 30, 33, 36])

In [133]:
data.sum(axis=1)

array([21, 57, 93])

In [134]:
data.min()

1

In [135]:
data.max()

18

In [137]:
data.min(axis=0)

array([1, 2, 3, 4, 5, 6])

In [138]:
data.min(axis=1)

array([ 1,  7, 13])

## Matrices

In [139]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [140]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [141]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [142]:
np.random.random((4, 5))

array([[0.52504701, 0.37391513, 0.82640107, 0.96243286, 0.10709271],
       [0.04276874, 0.79432869, 0.3023719 , 0.19645878, 0.94681308],
       [0.31902236, 0.53872773, 0.4164533 , 0.13992861, 0.63550212],
       [0.65965963, 0.34909933, 0.1490117 , 0.37973018, 0.15350745]])

In [143]:
data = np.array([[1, 2], [3, 4]])

In [144]:
ones = np.ones((2, 2))

In [145]:
data

array([[1, 2],
       [3, 4]])

In [146]:
ones

array([[1., 1.],
       [1., 1.]])

In [147]:
data + ones

array([[2., 3.],
       [4., 5.]])

In [148]:
data - ones

array([[0., 1.],
       [2., 3.]])

## Dot Product

In [149]:
a_1 = np.array([[1, 2, 3], [4, 5, 6]])

In [150]:
a_2 = np.array([[7, 8], [9, 10], [11, 12]])

In [151]:
a_1

array([[1, 2, 3],
       [4, 5, 6]])

In [152]:
a_2

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [153]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

## Indexing and Slicing

In [154]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [155]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [156]:
data[0]

array([1, 2])

In [157]:
data[1]

array([3, 4])

In [158]:
data[2]

array([5, 6])

In [160]:
data[1, 1]

4

In [161]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [165]:
data[0:2, 0]

array([1, 3])

In [166]:
data[:, 0]

array([1, 3, 5])

In [167]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

## Transposing

In [168]:
data.T

array([[1, 3, 5],
       [2, 4, 6]])

In [169]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [170]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

## N-Dimensional Array

In [172]:
np.ones((2, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [173]:
np.ones((3, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

## Flatten

In [174]:
data = np.ones((3, 3, 2))

In [175]:
data

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [177]:
data.flatten()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1.])